### ISSUE TITLE
Detailed setting info on anchor generation

### ISSUE THREAD

**Issue by jpstyle** [TalSchuster/CrossLingualELMo#11]
This is not an issue, but a question. Could you tell me more about how your anchors were generated for your experiments? The paper says anchors were computed from the evaluation set (which amounts to 5% of the total CoNLL data), but I'd like to know more details - like exactly how many sentences were used, for each language, etc.

Thanks!

**Comment by TalSchuster** [comment]
English - 6666885 sentences
es - 1470095
pt - 740945
it - 1307530
fr - 1887685
de - 3222565
sv - 1581915
