### ISSUE TITLE
What layer is aligned and what the English alignment matrix for?

### ISSUE THREAD

**Issue by OfirArviv** [TalSchuster/CrossLingualELMo#6]
Hi,

I've read your article and the readme here and I'm a little confused about 2 things:

1. You state  
> We provide the alignment of the first LSTM output of ELMo to English

and also:
> Note that our alignments were done on the second layer of ELMo

My understanding is that "fist LSTM output" is not the second layer. Am I misunderstanding the quote? What layer do you align?

2. If the alignment matrices aligned the models to the English model, what is the purpose of the English alignment matrix?

Thanks!

**Comment by TalSchuster** [comment]
Hi Ofir,

Sorry for the confusion. I've updated the README file now to have alignments for all 3 layers. The links in the table are for the first "contextualized" layer (after one layer of LSTM).

The English files simply contain the identity matrix divided by the average norm for that layer.

**Comment by OfirArviv** [comment]
Thank you for the clarification!
