### ISSUE TITLE
Few-shot training

### ISSUE THREAD

**Issue by niless** [TalSchuster/CrossLingualELMo#8]
Is it possible to train anchored LM for few-shot parsing?

**Comment by TalSchuster** [comment]
Hi @niless 
I'm not sure that I understand your question. The language models are to compute contextual embeddings.
These embeddings could be used for any downstream task including few-shot parsing. In the paper, we've demonstrated few-shot parsing results for Kazakh from Turkish.

Feel free to shoot me an email with more details if this doesn't answer your question
